zadatak_niz_brojeva
npetrovic-endava/nada-java-zadaci pull request #11
Opened 2018-09-10 15:08 UTC by npetrovic-endava

2018-09-10 19:05 UTC, mpaunovi commented on src/zadatak7/NizBrojeva.java
> +	static Scanner ulaz = new Scanner(System.in);
fali zatvaranje ulaz vrednosti.

2018-09-11 07:44 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +	public static String brojPripadaNizu(int x, int a[]) {
int a[]  se nigde ne koristi u ovoj metodi

2018-09-11 07:47 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +			System.out.println("Unesite clan niza:");
promeni komentar, da bi bilo jasnije onome ko unosi clanove
 Unesite 1,2, 3.. clan niza...

2018-09-11 14:59 UTC, c0mmrade requested changes

2018-09-11 14:59 UTC, c0mmrade commented on src/zadatak7/NizBrojeva.java
> +*/
Jedan javadoc, i ide iznad imena klase

2018-09-11 14:59 UTC, c0mmrade commented on src/zadatak7/NizBrojeva.java
> +			System.out.println("Uneti broj clanova niza veci ili jednak broju 5:");
Molim te tekst iz koda prebaci u konstante

2018-09-11 14:59 UTC, c0mmrade commented on src/zadatak7/NizBrojeva.java
> +	public static String brojPripadaNizu(int x) {
ovo je privatna metoda...

2018-09-11 14:59 UTC, c0mmrade commented on src/zadatak7/NizBrojeva.java
> +	}
imas nekih redova vishka ovde :)

2018-09-11 14:59 UTC, c0mmrade commented on src/zadatak7/NizBrojeva.java
> +				return "Broj ne pripada nizu.";
Hajde da ne koristimo multiple return pointe... 
mozhesh npr da uvedesh boolean vrednost: 
boolean pripadaNizu = false; 
onda krenesh u petlju 
for (int i=0; i<clanovi, i++) { 
  if(x==niz[i]) { 
    pripadaNizu=true;
    break;
  }
}
i posle vratish kondicionalno vrednost 
npr: 
return pripadaNizu ? ISPIS_PRIPADA : ISPIS_NE_PRIPADA ;

2018-09-17 12:11 UTC, BoskoNikolic requested changes

2018-09-17 12:11 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +	public static Scanner ulaz = new Scanner(System.in);
od linije 17 do 26 sve promneljive i konstante da budu private

2018-09-17 12:11 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +	public static int niz[];
int[]  niz

2018-09-17 12:11 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +		while (true) {
uvedi neki boolean i vrti se u petlji sve kod ne postane false

2018-09-18 10:24 UTC, BoskoNikolic requested changes

2018-09-18 10:24 UTC, BoskoNikolic commented on src/zadatak7/NizBrojeva.java
> +		uslov=false;
sad si samo ubila program posle jednog run-a :) poenta je da koristis samo jedno break ili boolean. Pokreni program pre nego sto ga okasis.

2018-09-19 22:29 UTC, mpaunovi approved these changes

2018-09-19 22:29 UTC, mpaunovi commented on src/zadatak7/NizBrojeva.java
> +		while (true) {
proveriti formatiranje

2018-09-19 22:29 UTC, mpaunovi commented on src/zadatak7/NizBrojeva.java
> +           //ispituje da li je unos broja clanova niza korektan
formatiranje

2018-09-19 22:29 UTC, mpaunovi commented on src/zadatak7/NizBrojeva.java
> +			System.out.println(niz[i]);
ispis u jednom redu

2018-09-19 22:29 UTC, mpaunovi commented on src/zadatak7/NizBrojeva.java
> +		Arrays.sort(niz);
mogla bi da se kreira posebna metoda za sortiranje koja kao argument dobija niz.

2018-09-21 08:10 UTC, merged