dodajem zadatak student
npetrovic-endava/nada-java-zadaci pull request #12
Opened 2018-09-11 11:25 UTC by npetrovic-endava

2018-09-11 14:53 UTC, c0mmrade requested changes

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> + */
Stavi ovo sve u jedan javadoc, nema potrebe za razdvajanjem

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +	static Scanner ulaz = new Scanner(System.in);
private static

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +		String imeNajboljegStudenta = "";
Bolje da dodelish "null" vrednost nego empty string... Ili da deklarishesh kao varijablu gde i ulaz, kao String imeNajboljegStudenta; i posle koristish kad mu dodelish vrednost

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +		String komentar1 = "Unesite broj studenata:";
A hajde da izbacimo tekst iz koda, molim te
znachi proglasi konstante na pochetku: 
public static final String BROJ_STUDENATA_ISPIS = "Unesite broj studenata: "; 
i tako za sve ostale

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +	static int proveraInt() {
ova metoda ima package access, bez ikakve potrebe... stavi da bude private

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +	static int proveraBroj(int n) {
private...

2018-09-11 14:53 UTC, c0mmrade commented on src/zadatak4/Student.java
> +			System.out.println(new StringBuilder("Ime najboljeg studenta je ").append(imeNajboljegStudenta).toString());
Chist primer zashto koristimo konstante :) 
new StringBuilder(NAJBOLJI_STUDENT_ISPIS).append(imeNajboljegStudenta).toString();

2018-09-17 12:15 UTC, BoskoNikolic approved these changes

2018-09-17 12:15 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +		String imeStudenta = null;
nema razloga za inicijalizacijom

2018-09-17 14:13 UTC, merged