dodajem zadatak 9
npetrovic-endava/nada-java-zadaci pull request #15
Opened 2018-09-12 15:14 UTC by npetrovic-endava

2018-09-17 12:22 UTC, BoskoNikolic requested changes

2018-09-17 12:22 UTC, BoskoNikolic commented on src/zadatak9/Kuca.java
> +	public int Multiplikator(int zona) {
imena metoda pocinju malim slovom

2018-09-17 12:22 UTC, BoskoNikolic commented on src/zadatak9/Kuca.java
> +		double cena = getKvadratura() * Multiplikator(getZona())
odmah vrati ovu vrednost, bez uvodjenja dodatne promenljive

2018-09-17 12:22 UTC, BoskoNikolic commented on src/zadatak9/Nekretnina.java
> +	Vlasnik vlasnik;
private

2018-09-17 12:22 UTC, BoskoNikolic commented on src/zadatak9/Stan.java
> +		double cena = getKvadratura() * Multiplikator(getZona())
odmah vrati vrednost izraza, bez uvodjenja dodatne promenljive

2018-09-17 12:22 UTC, BoskoNikolic commented on src/zadatak9/Stan.java
> +	public int Multiplikator(int zona) {
ime metode pocinje malim slovom

2018-09-19 22:34 UTC, mpaunovi approved these changes

2018-09-21 07:55 UTC, BoskoNikolic approved these changes

2018-09-21 07:56 UTC, merged