Zadatak 12
npetrovic-endava/nada-java-zadaci pull request #17
Opened 2018-09-14 10:57 UTC by npetrovic-endava

2018-09-17 12:03 UTC, BoskoNikolic requested changes

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	private ArrayList<Lekar> lekari;
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	private ArrayList<Osoblje> osoblje;
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	private ArrayList<MedicinskeSestre> sestre;
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public Bolnica(String nazivBolnice, String imeDirektora, ArrayList<Lekar> lekari, ArrayList<Osoblje> osoblje,
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public ArrayList<Lekar> getLekari() {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public void setLekari(ArrayList<Lekar> lekari) {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public ArrayList<Osoblje> getOsoblje() {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public void setOsoblje(ArrayList<Osoblje> osoblje) {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public ArrayList<MedicinskeSestre> getSestre() {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +	public void setSestre(ArrayList<MedicinskeSestre> sestre) {
Koristi List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +		int brojSestara = sestre.size();
odmah vrati ovu vrednost, nemoj uvoditi novu promenljivu bez potrebe.

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +		return brojLekara;
odmah vrati ovu vrednost, nemoj uvoditi novu promenljivu bez potrebe.

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Bolnica.java
> +		return brojOsoblja;
odmah vrati ovu vrednost, nemoj uvoditi novu promenljivu bez potrebe.

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Firma.java
> +	private ArrayList<Bolnica> bolnice;
List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Firma.java
> +	public ArrayList<Bolnica> getBolnice() {
List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Firma.java
> +	public void setBolnice(ArrayList<Bolnica> bolnice) {
List umesto ArrayList

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Test.java
> +		ArrayList<Lekar> nizLekara1 = new ArrayList<>();
List umesto ArrayList  - primeni to na citavu klasu

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Zaposleni.java
> +		if (true == proveraDatuma(datumRodjenja)) {
Nema potrebe da proveravas da li je boolean true, samo if (proveraDatuma(datumRodjenja))

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Zaposleni.java
> +	private final String PORUKA_ZA_POGRESNO_IME = "Nije unet pravilan podatak za ime";
od linije 15 do linje 20 sve konstante bi trebalo da budu private static final String

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Zaposleni.java
> +		if (true == proveraDatuma(datumRodjenja)) {
Nema potrebe da proveravas da li je boolean true, samo if (proveraDatuma(datumRodjenja))

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak11/Zaposleni.java
> +		boolean provera = false;
Nema potrebe da ovde dodeljujes vrednost booleanu, kada se ona nigde nece koristiti.

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak12/StudentiIspis.java
> +	private static Student student;
moze da bude lokalna promenljiva definisana u liniji 85

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak12/StudentiIspis.java
> +	private static PrintWriter pw;
moze da bude lokalna promenljiva definisana u liniji 46

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak12/StudentiIspis.java
> + * Napisati program koji umogucava unos imena studenta i broj poena osvojenih na testu preko
ispravi typo u java doc-u

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak12/StudentiIspis.java
> +		System.out.println(studenti);
nemoj da stampas sve u jednoj liniji

2018-09-17 12:03 UTC, BoskoNikolic commented on src/zadatak12/StudentiIspis.java
> +			if (ime.contains("#")) {
Neko ko ne zna kako izgleda kod, nece moci da izadje iz programa. ispisi neko poruku koje govori koji karakter treba da se unese za prekid unosa. 

takodje mozda nije lose da umesto while(true) {break} uvedes neku promenljivu koju ces setovati na true ili false u zavisnosti od toga da li je unet # ili ne .

2018-09-19 23:13 UTC, mpaunovi commented on src/zadatak11/Bolnica.java
> +		int brojSestara = sestre.size();
+1

2018-09-19 23:13 UTC, mpaunovi commented on src/zadatak11/Zaposleni.java
> +	private final String PORUKA_ZA_POGRESNO_IME = "Nije unet pravilan podatak za ime";
+1 i za ovo

2018-09-19 23:15 UTC, mpaunovi requested changes
Potrebne promene prema komentarima

2018-09-20 09:51 UTC, closed without merging