dodajem zadatak Student
npetrovic-endava/nada-java-zadaci pull request #5
Opened 2018-09-10 08:32 UTC by npetrovic-endava

2018-09-10 09:07 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +            int n = proveraInt();
proveraInt i proveraBroj mogu da se spoje u jednu metodu.

2018-09-10 09:09 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +        if (n <= 0) {
i if i while imaju istu uslov, nesto je visak ;)

2018-09-10 09:12 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +                    poeni = maxPoeni;
Dodeljena vrednost ovde nikak nece biti iskoriscena

2018-09-10 09:19 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +        if (n <= 0) {
If i while imaju isti uslov

2018-09-10 09:20 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +            int n = proveraInt();
proveraInt i proveraBroj verovatno mogu da se spoje u jednu metodu

2018-09-10 09:21 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +        int maxPoeni = 0;
Zasto dodeljujes ovu vrednost?

2018-09-10 09:22 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +                    poeni = maxPoeni;
Ovde dodeljena vrednost promenljivoj poeni, nece nikad biti iskoriscena

2018-09-10 09:23 UTC, BoskoNikolic commented on src/zadatak4/Student.java
> +            for (int i = 0; i < n; i++) {
Da li si probala situaciju u kojoj je uneti broj bodova 0 ili negativan ?

2018-09-10 09:26 UTC, BoskoNikolic requested changes
Program nece raditi za granicne slucajeve
- osvojeni bodovi 0 ili negativni.

Postoje sitne greske u pisanju metoda, ostavljeni su komentari.

2018-09-11 11:19 UTC, c0mmrade requested changes
Hajde josh par stvari: 

1. Izbaci tekst iz koda, Mozhesh da napravish konstante za sve shto koristish. Em preglednije, em mozhesh da re-useujesh po potrebi 
2. Dodeljuj smislena imena variablama, pa i iteratorima. Neka ti ime promenjive bude "komentar" 
3. Ima li smisla da neke od metoda (tipa proveraBroja) budu u zasebnoj klasi ?

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +        StringBuilder sb = new StringBuilder("Najbolji student je: ");
Nema potrebe da se inicijalizuje sb, bolje je da ga pozivas u ispisu. 
Sama konstrukcija pravljenja string buildera koji storuje vrednost stringa nije dobra. Takodje fali .toString();

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +            for (int i = 0; i < n; i++) {
Da li mozemo da dodelimo neko smisleno ime iteratoru?

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +            System.out.println(sb.append(imeNajboljegStudenta));
Bas kao sto rekoh, bolja varijanta je ovde kreirati builder: 
new StringBuilder(text pattern).append(imeStudenta...).toString();

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +    public static String proveraString() {
zasto ti je ovo public?

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +    public static int proveraInt() {
zasto ti je ovo public?

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> +    public static int proveraBroj(int n) {
zasto ti je ovo public?

2018-09-11 11:19 UTC, c0mmrade commented on src/zadatak4/Student.java
> + * @author Nadezda Petrovic
Javadoc treba da ti bude iznad imena klase 
Kao i ovaj deo sa opisom.

2018-09-14 12:31 UTC, closed without merging

2018-09-14 12:32 UTC, npetrovic-endava commented
za zadatak student vec imam pull request